### ISSUE TITLE
Popover not selected

### ISSUE THREAD

**Issue by river** [aschuch/AXStatusItemPopup#1]
Hey, thanks for sharing this great class! It's very helpful for me to figure out NSPopover, as I'm still unfamiliar with obj-c. I'm running into a bit of a problem trying to use it though. Buttons, text fields, etc. in the popover remain inactive after the popover gets shown. In fact, text fields seem to be completely uneditable.

I'm pretty sure this isn't anything specific to my project, since the same problem occurs when I add a text field to the demo project (see screenshot).

![screenshot](http://i.imgur.com/8VVWYAl.png)

I've spent a while trying to figure out what's going wrong, but I have no idea. My only thought right now is that perhaps it's because the `NSPopover` is being called by an `NSViewController`, rather than an `NSWindowController <NSPopoverDelegate>` (but again, I'm unfamiliar with obj-c, so this may be irrelevant).

**Comment by aschuch** [comment]
I did some research and found the same issue with `NSTextField`. 
Apparently this is a bug introduced in OS X Lion.

The following category on `NSWindow` fixed it for me (just create a category and add it to your project).

NSWindow+canBecomeKeyWindow.h

``` objective-c
#import <Cocoa/Cocoa.h>

@interface NSWindow (canBecomeKeyWindow)

@end
```

NSWindow+canBecomeKeyWindow.m

``` objective-c
#import "NSWindow+canBecomeKeyWindow.h"

@implementation NSWindow (canBecomeKeyWindow)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-protocol-method-implementation"
- (BOOL)canBecomeKeyWindow
{
    return YES;
}
#pragma clang diagnostic pop

@end
```

**Comment by amccloud** [comment]
When I implement this it requires two clicks to open the popover. The code below appears to work as expected. Make sure you change `DVAppDelegate` to your app delegate class.

``` objectivec
#import "NSWindow+canBecomeKeyWindow.h"

@implementation NSWindow (canBecomeKeyWindow)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-protocol-method-implementation"
- (BOOL)canBecomeKeyWindow
{
    if([self class] == NSClassFromString(@"NSStatusBarWindow")) {
        DVAppDelegate *appDelegate = [NSApp delegate];
        return appDelegate.statusItemPopup.isActive;
    }

    return NO;
}
#pragma clang diagnostic pop
@end
```
