### ISSUE TITLE
Problems with 10.10

### ISSUE THREAD

**Issue by copa** [aschuch/AXStatusItemPopup#14]
The icon in the status bar will not appear. This code should solve the issue. 

``` obj-c
- (void)drawRect:(NSRect)dirtyRect{
    [self.statusItem drawStatusBarBackgroundInRect:dirtyRect withHighlight:self.isActive];

    NSImage *icon = self.isActive ? self.alternateImage : self.image;
    NSSize iconSize = [icon size];
    NSRect bounds = self.bounds;
    CGFloat iconX = roundf((NSWidth(bounds) - iconSize.width) / 2);
    CGFloat iconY = roundf((NSHeight(bounds) - iconSize.height) / 2);
    NSPoint iconPoint = NSMakePoint(iconX, iconY);

    [icon drawAtPoint:iconPoint fromRect:NSZeroRect operation:NSCompositeSourceOver fraction:1.0];
    }
```

In addition I would change the declaration of the private interface. I saw this code in PR #7

**Comment by aschuch** [comment]
Can you make a pull request covering these changes?
Unfortunately, I'm not on 10.10. yet, could you share some before/after screenshots as well?

**Comment by copa** [comment]
Yes I will open a PR ... but plz give me a few days for better investigation. Maybe it would make sense to wait for a 2nd beta.

**Comment by jeff-h** [comment]
I've just installed the public beta of 10.10 and the icon appears in the status bar fine for me, without the code above.

**Comment by copa** [comment]
Yes, I can confirm the correct behaviour on 10.10. (14A329f)
