### ISSUE TITLE
Close when losing focus

### ISSUE THREAD

**Issue by deplorableword** [aschuch/AXStatusItemPopup#3]
Hi,

Is there a simple way to hide the popover when it loses focus? For example if the user clicks anywhere else but inside the window or on another status bar item?

**Comment by aschuch** [comment]
Hey,

your issue got fixed as of 9a015cb4033824d98082de9605ceedfe3d0c5cd6.
The popover now hides automatically when you click anywhere outside.

Thanks again, @adamhartford.
