### ISSUE TITLE
Fast clicking on OSX causes over-releasing of _popoverTransiencyMonitor

### ISSUE THREAD

**Issue by ghost** [aschuch/AXStatusItemPopup#9]
I noticed that triple-clicking on the menu bar icon causes a crash in the UI thread. After some debugging, I have found the cause & a (potential) fix.

Original:

```
- (void)hidePopover
{
    self.active = NO;

    if (_popover && _popover.isShown) {
        [_popover close];
        [NSEvent removeMonitor:_popoverTransiencyMonitor];
    }
}
```

Fix:

```
- (void)hidePopover
{
    self.active = NO;
    if (_popover && _popover.isShown) {
        [_popover close];
        if (nil != _popoverTransiencyMonitor) {
            [NSEvent removeMonitor:_popoverTransiencyMonitor];
            _popoverTransiencyMonitor = nil;
        }
    }
}
```

From the Apple Docs:

**_Remove the specified event monitor. You must ensure that eventMonitor is removed only once. Removing the same eventMonitor instance multiple times results in an over-release condition, even in a Garbage Collected environment.**_

**Comment by aschuch** [comment]
Thanks, fixed!
